const CREATE_NOTEBOOK = 'notebook/CREATE_NOTEBOOK'
const LOAD_NOTEBOOKS = 'notebook/LOAD_NOTEBOOKS'
const UPDATE_NOTEBOOK = 'notebook/UPDATE_NOTEBOOK'
const DELETE_NOTEBOOK = 'notebook/DELETE_NOTEBOOK'
